# Generated by Django 5.1.2 on 2024-10-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_school', '0006_material_rating_scheduledclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledclass',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='enrolled_students',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='assigned',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ScheduledClass',
        ),
    ]
