# Generated by Django 5.1.2 on 2024-10-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_school', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
